### ISSUE TITLE
Scaling Factor ODIN

### ISSUE THREAD

**Issue by matteoguarrera** [wetliu/energy_ood#10]
As stated by your readme your implementation is based on: 
In particular, I would like to understand the following lines:
https://github.com/wetliu/energy_ood/blob/77f3c09b788bb5a7bfde6fd3671228320ea0949c/utils/score_calculation.py#L67-L69

It seems there is an issue here. The original code is:

https://github.com/pokaxpoka/deep_Mahalanobis_detector/blob/90c2105e78c6f76a2801fc4c1cb1b84f4ff9af63/lib_generation.py#L171-L178

Thanks for your time

**Comment by weitliu** [comment]
We did notice this issue and it seems to be a consistency problem of merging all different implementation code. This scaling factor is determined by TRAINING scale which is the same as https://github.com/hendrycks/outlier-exposure/blob/master/CIFAR/test.py/#L49. We believe switching to a different scaling during TEST time using Mahalanobis distance leads to unfair results, so we use the same scaling for all the other methods.
