### ISSUE TITLE
Test samples from places365

### ISSUE THREAD

**Issue by lygjwy** [wetliu/energy_ood#20]
Hello! Thank you for your excellent work and I wonder about the test samples used in the places365 experiment. Did you use all the 328500 samples from places365 or randomly sample 10000 images? If randomly sampling, can you provide the images' name list for experiment reproduction? Thank you!

**Comment by weitliu** [comment]
Thank you for reaching out. Please refer to [this issue](https://github.com/hendrycks/outlier-exposure/issues/2).

**Comment by lygjwy** [comment]
> Thank you for reaching out. Please refer to [this issue](https://github.com/hendrycks/outlier-exposure/issues/2).

Get. Thank you for your reply.
