### ISSUE TITLE
Multivarite unsupervised time series data

### ISSUE THREAD

**Issue by jyoti922** [wetliu/energy_ood#22]
hi, can you guide me on how to use it well for multivariate unsupervised time series data?
Do we need to use encoder and decoder kind of pattern firstly then for reconstruction error calculation method use energy-based method? Similarly GAN based reconstruction error calculation method. 

If you can guide me it will be too helpful

**Comment by weitliu** [comment]
I think it can apply to the discriminator of the GAN models.
