### ISSUE TITLE
The datasets of LSUN-Crop and LSUN-Resize

### ISSUE THREAD

**Issue by JimZAI** [wetliu/energy_ood#25]
What a remarkable work. Thanks for bringing me a lot of inspirations.

When i reproduce the results, i cannot find the two datasets of LSUN-Crop and LSUN-Resize in this repo or Outlier-Exposure (other datasets were found). Could you tell me where to download the two datasets.

Many thanks.

**Comment by YixuanLi** [comment]
Thanks for your interest in our work. If you scroll down to the bottom of the GitHub page, the downloadable link is attached for those two datasets. 

https://www.dropbox.com/s/moqh2wh8696c3yl/LSUN_resize.tar.gz
https://www.dropbox.com/s/fhtsw1m3qxlwj6h/LSUN.tar.gz
