### ISSUE TITLE
How to arrange dataset for optimal m_in and m_out values?

### ISSUE THREAD

**Issue by utkutpcgl** [wetliu/energy_ood#28]
Thanks for the great contribution!

To optimize m_in and m_out how did you arrange the validation dataset. I see that you have used 10% from the cifar10 dataset here:
https://github.com/wetliu/energy_ood/blob/77f3c09b788bb5a7bfde6fd3671228320ea0949c/CIFAR/train.py#L93

Did you use the entire auxiliary dataset (tiny images) to measure the OOD performance of the chosen parameters (m_in and m_out)?

**Comment by weitliu** [comment]
#13
