### ISSUE TITLE
Why is shuffle set to False for the train OOD dataloader?

### ISSUE THREAD

**Issue by utkutpcgl** [wetliu/energy_ood#29]
Thanks for the contribution.

Why didn't you shuffle the OOD dataset to induce randomness?
https://github.com/wetliu/energy_ood/blob/77f3c09b788bb5a7bfde6fd3671228320ea0949c/CIFAR/train.py#L106

Instead, randomness is induced by changing the dataset offset, why is that?
https://github.com/wetliu/energy_ood/blob/77f3c09b788bb5a7bfde6fd3671228320ea0949c/CIFAR/train.py#L177

**Comment by weitliu** [comment]
#2
