### ISSUE TITLE
The influence of "exclude_cifar"?

### ISSUE THREAD

**Issue by JimZAI** [wetliu/energy_ood#30]
Hi, thank you for your insightful work.

When i reproduced the results, I found that the results are consistent/unchanged when setting the parameter "exclude_cifar" (in tinyimages_80mn_loader.py) to be Ture or False. That indicates filtering out CIFAR data in the auxiliary outlier dataset is not necessary? I believe it does not make sence. Could you please tell me the possible reasons for this.

Thanks a lot.

**Comment by weitliu** [comment]
80,000,000 is way larger than the cifar datasets.
