### ISSUE TITLE
how to decide energy threshold? how to write code？#6

### ISSUE THREAD

**Issue by fgghhsha123** [wetliu/energy_ood#32]
# code:
fpr, tpr, ood_thre = roc_curve(labels, scores, pos_label=0)
# output:
         fpr       tpr   ood_thre
0  0.000000  0.0   0.623103
1  0.001042  0.0  -0.376897
2  1.000000  0.0  -1.332735
3  1.000000  1.0 -24.738714

the output of the roc_curve function did not output a situation where tpr equals 0.95 or above, so the corresponding threshold cannot be determined. How did you implement the method in # 6?

**Comment by weitliu** [comment]
It should be here: https://github.com/wetliu/energy_ood/blob/master/utils/display_results.py#L69
