### ISSUE TITLE
do you have the link for the tiny image dataset?

### ISSUE THREAD

**Issue by d12306** [wetliu/energy_ood#5]
Hi, @wetliu , do you have the link for the tiny images used in fine-tuning, this dataset is offline now.

Thanks,

**Comment by weitliu** [comment]
No, we don't find active link available now.

**Comment by YixuanLi** [comment]
Please consider using an alternative outlier dataset ImageNet-RC.

**Comment by weitliu** [comment]
@d12306 Please refer to [Outlier-exposure](https://github.com/hendrycks/outlier-exposure), which has a mirror link for downloading this dataset at the bottom of their homepage.

**Comment by tongwu2020** [comment]
> @d12306 Please refer to [Outlier-exposure](https://github.com/hendrycks/outlier-exposure), which has a mirror link for downloading this dataset at the bottom of their homepage.

Hi, it seems the mirror link is unavailable. Thanks.
