### ISSUE TITLE
how to decide energy threshold?

### ISSUE THREAD

**Issue by Haijunlv** [wetliu/energy_ood#6]
hi, your paper said that "In practice, we choose the threshold using in-distribution data so that a high fraction of inputs are correctly classified by the OOD detector G(x)."
But in your code, i cannot find the way to decide energy threshold.
could you give a example of deciding energy threshold?
i supposed that we can decide threshold  by od and id scores with best fpr.
But i do not konw if we can decide threshold simply by  in-distribution data?

![image](https://user-images.githubusercontent.com/28926237/104891777-562d7a00-59ac-11eb-8a98-69d60fd8f0f8.png)

**Comment by weitliu** [comment]
For example, if we choose FPR95, which means 95% of the in-distribution data is classified correctly, then the energy corresponded to this 95% accuracy is the threshold.

**Comment by Jinsol-Lee** [comment]
Hi, I took a look at the ranges of scores from in-distribution data and ood data and they seem to be so different that the threshold value obtained in the way you described above would not work on the ood data. Could you disclose the threshold values you used to generate results from the tables in the paper? Thank you!
